#!/bin/sh -x

#
# Installation script for seqdeleter
#
# 1) cp gbseqdeleter.config.default gbseqdeleter.config
# 2) cp refseqdeleter.config.default refseqdeleter.config
# 3) cp seqdeleter_common.config.default seqdeleter_common.config
# 2) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the three config files
GB_CONFIG=gbseqdeleter.config
RS_CONFIG=refseqdeleter.config 
COMMON_CONFIG=seqdeleter_common.config

# Make sure gbseqdeleter.config file exists and source it
if [ -r ${GB_CONFIG} ]
then
    echo "Source ${GB_CONFIG}"
    . ${GB_CONFIG}
else
    echo "Cannot source configuration file: ${GB_CONFIG}"
    installFailed
fi

# Make sure seqdeleter_common.config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""
echo "DEV=${DEV}"
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for gbseqdeleter
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

# now do refseqdeleter
# Make sure refseqdeleter.config file exists and source it
if [ -r ${RS_CONFIG} ]
then
    echo "Source ${RS_CONFIG}"
    . ${RS_CONFIG}
else
    echo "Cannot source configuration file: ${RS_CONFIG}"
    installFailed
fi

# source seqdeleter_common.config again
. ${COMMON_CONFIG}

#
# run DLAInstall for refseqdeleter
#
${DLAINSTALL} ${DEV}

